{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vouch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vouch.name" . }}
    helm.sh/chart: {{ include "vouch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  config.yaml: |
    {{- if .Values.config.vouch }}
    vouch:
      port: {{ .Values.config.vouch.port }}
      logLevel: {{ .Values.config.vouch.logLevel }}
      testing: {{ .Values.config.vouch.testing }}
      domains:
      {{ toYaml .Values.config.vouch.domains | indent 8 }}
      whiteList:
      {{ toYaml .Values.config.vouch.whiteList| indent 8 }}
      allowAllUsers: {{ .Values.config.vouch.allowAllUsers }}
      {{- if .Values.config.vouch.jwt.secret }}
      jwt:
        secret: {{ .Values.config.vouch.jwt.secret }}
      {{- end }}
    {{- end }}
    {{- if .Values.config.oauth }}
    oauth:
      provider: {{ .Values.config.oauth.provider }}
      client_id: {{ .Values.config.oauth.clientId }}
      client_secret: {{ .Values.config.oauth.clientSecret }}
      {{- if .Values.config.oauth.authUrl }}
      auth_url: {{ .Values.config.oauth.authUrl }}
      {{- end }}
      {{- if .Values.config.oauth.tokenUrl }}
      token_url: {{ .Values.config.oauth.tokenUrl }}
      {{- end }}
      {{- if .Values.config.oauth.userInfoUrl }}
      user_info_url: {{ .Values.config.oauth.userInfoUrl }}
      {{- end }}
      {{- if .Values.config.oauth.scopes }}
      scopes:
      {{ toYaml .Values.config.oauth.scopes | indent 8 }}
      {{- end }}
      {{- if .Values.config.oauth.callbackUrls }}
      callback_urls:
      {{ toYaml .Values.config.oauth.callbackUrls | indent 8 }}
      {{- end }}
      preferredDomain: {{ .Values.config.oauth.preferredDomain }}
    {{- end }}
{{- end }}
